<a href="https://colab.research.google.com/github/kimve1969/mgu_ds_cours/blob/main/semestr%202.1/task%201/semestr_2_1_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ВМК МГУ, Курс по Data Science (DS) и Machine Learning (ML) 2026 год
2 семестр, Анализ данных в Python,
Ким Виталий Евгеньевич, ПАО "Сургутнефтегаз"
19.07.2026

Постановка задачи

Будем работать с данными о клиентах банка, который интересуется, произойдет ли просрочка платежа на 90 и более дней при выдаче кредита.

1. Прочтите данные из файла data.csv Функции, которые могут пригодиться при решении: pd.read_csv(..., delimiter=',')
2. Выведите описание прочтенных данных. Функции, которые могут пригодиться при решении: .describe()
3. Отобразите несколько первых и несколько последних записей. Функции, которые могут пригодиться при решении: .head(), .tail() Какие параметры можно передать этим функциям?
4. Прочтите в файле DataDictionary-ru.txt, что означают столбцы матрицы. Какому типу принадлежит каждый столбец (вещественный, целый, категориальный)?
5. Заметьте, что столбец DebtRatio содержит неправдоподобные данные. Только значения, соответствующие известному месячному доходу, являются отношениями. Остальные – абсолютные значения месячных выплат процентов. Исправьте данные, сделав все значения столбца DebtRatio абсолютными (умножьте их на MonthlyIncome). Чтобы ваша программа быстро работала на полных данных, постарайтесь не использовать цикл.
6. Поменяйте имя столбца на Debt. Функции, которые могут пригодиться при решении: .rename(columns= {'староеИмя':'новоеИмя'}, inplace=True)
7. Вычислите средний ежемесячный доход и присвойте всем клиентам с неизвестным доходом полученное число.
8. Используя метод groupby, оцените вероятности невозврата кредита (SeriousDlqin2yrs=1) для различных значений количества иждивенцев (NumberOfDependents). Проделайте аналогичную процедуру для различных значений столбца NumberRealEstateLoansOrLines

# ВЫПОЛНЕНИЕ

In [36]:
import pandas as pd

# читаем файл из github
df = pd.read_csv('https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%201/data.csv')

# читаем хедер
df.head(10)

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,6,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,7,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,8,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,9,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,10,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0

In [37]:
from os import read
import urllib.request

# описание полей
urllib.request.urlretrieve('https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%201/DataDictionary-ru.txt', 'DataDictionary-ru.txt')

with open('DataDictionary-ru.txt','r') as f:
  for line in f:
    line = line.rstrip('\n')
    print(line)

SeriousDlqin2yrs
Произойдет ли просрочка платежа на 90 или более дней в ближайшие 2 года (Y/N)

RevolvingUtilizationOfUnsecuredLines
Процент оставшихся денег на всех кредитных картах   (%)

age
Возраст (integer)

NumberOfTime30-59DaysPastDueNotWorse
Количество кратковременных просрочек платежа (30-59 дней) за последние 2 года   (integer)

DebtRatio
Выплачиваемые в месяц проценты от долга, алименты, бытовые расходы, деленные на месячный доход (если месячный доход неизвестен, то абсолютная величина выплат)  (%)

MonthlyIncome
Месячный доход  (real)

NumberOfOpenCreditLinesAndLoans
Количество кредитов (или кредитных карт) за исключением ипотеки (integer)

NumberOfTimes90DaysLate
Кредитная история: количество серьезных просрочек платежа на 90 дней или более (integer)

NumberRealEstateLoansOrLines
Количество ипотек   (integer)

NumberOfTime60-89DaysPastDueNotWorse
Количество среднесрочных просрочек платежа (60-89 дней) за последние 2 года (integer)

NumberOfDependents
Количество иждивенцев в семье, включая самого клиента   (integer)

In [38]:
# Меняем названия полей
df.rename(columns={'SeriousDlqin2yrs':'Прогноз просрочки в течении 2 лет',
                   'RevolvingUtilizationOfUnsecuredLines':'Остаток на кред.картах, %',
                   'age':'Возраст',
                   'NumberOfTime30-59DaysPastDueNotWorse':'Кол-во просрочек 30-59 дней',
                   'DebtRatio':'Платежей от долга, % или абс.платеж',
                   'MonthlyIncome':'Месячный доход',
                   'NumberOfOpenCreditLinesAndLoans':'Кол-во кредитов',
                   'NumberOfTimes90DaysLate':'Кол-во просрочек на 90 дней и более',
                   'NumberRealEstateLoansOrLines':'Кол-во ипотек',
                   'NumberOfTime60-89DaysPastDueNotWorse':'Кол-во сред.просрочек (60-89 дней) за 2 года',
                   'NumberOfDependents':'Кол-во иждевенцев в семье'}, inplace=True)
df

,Id,Прогноз просрочки в течении 2 лет,"Остаток на кред.картах, %",Возраст,Кол-во просрочек 30-59 дней,"Платежей от долга, % или абс.платеж",Месячный доход,Кол-во кредитов,Кол-во просрочек на 90 дней и более,Кол-во ипотек,Кол-во сред.просрочек (60-89 дней) за 2 года,Кол-во иждевенцев в семье
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1346,0,0.000000,39,0,0.055916,4166.0,5,0,0,0,0.0
1346,1347,0,0.045694,49,0,0.300175,4000.0,14,0,1,0,1.0
1347,1348,0,0.022780,53,0,0.323068,10000.0,14,0,2,0,1.0
1348,1349,0,0.036934,56,0,0.287935,8362.0,8,0,1,0,2.0
1349,1350,0,0.000000,62,0,1463.000000,NaN,5,0,1,0,0.0

In [39]:
df[df['Месячный доход'].isna() == False].head(2)
# ПОХОЖЕ В ОПИСАНИИ ПОЛЕЙ 'Остаток на кред.картах, %' и 'Платежей от долга, % или абс.платеж' ОШИБКА
# величины скорее всего выраженны в долях, а не % !!!

,Id,Прогноз просрочки в течении 2 лет,"Остаток на кред.картах, %",Возраст,Кол-во просрочек 30-59 дней,"Платежей от долга, % или абс.платеж",Месячный доход,Кол-во кредитов,Кол-во просрочек на 90 дней и более,Кол-во ипотек,Кол-во сред.просрочек (60-89 дней) за 2 года,Кол-во иждевенцев в семье
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0

In [40]:
# Корректируем "Платежей от долга..."
df['Платежей от долга, % или абс.платеж'] = df[df['Месячный доход'].isna() == False]['Платежей от долга, % или абс.платеж']*df['Месячный доход']
df

,Id,Прогноз просрочки в течении 2 лет,"Остаток на кред.картах, %",Возраст,Кол-во просрочек 30-59 дней,"Платежей от долга, % или абс.платеж",Месячный доход,Кол-во кредитов,Кол-во просрочек на 90 дней и более,Кол-во ипотек,Кол-во сред.просрочек (60-89 дней) за 2 года,Кол-во иждевенцев в семье
0,1,1,0.766127,45,2,7323.197016,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,316.878123,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,258.914887,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,118.963951,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,1584.975094,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1346,0,0.000000,39,0,232.944085,4166.0,5,0,0,0,0.0
1346,1347,0,0.045694,49,0,1200.699824,4000.0,14,0,1,0,1.0
1347,1348,0,0.022780,53,0,3230.676930,10000.0,14,0,2,0,1.0
1348,1349,0,0.036934,56,0,2407.712069,8362.0,8,0,1,0,2.0
1349,1350,0,0.000000,62,0,NaN,NaN,5,0,1,0,0.0

In [41]:
df.describe()

,Id,Прогноз просрочки в течении 2 лет,"Остаток на кред.картах, %",Возраст,Кол-во просрочек 30-59 дней,"Платежей от долга, % или абс.платеж",Месячный доход,Кол-во кредитов,Кол-во просрочек на 90 дней и более,Кол-во ипотек,Кол-во сред.просрочек (60-89 дней) за 2 года,Кол-во иждевенцев в семье
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1094.000000,1094.000000,1350.000000,1350.000000,1350.000000,1350.000000,1307.000000
mean,675.500000,0.060000,3.577895,52.048889,0.257778,2032.285613,6438.473492,8.434074,0.080000,0.986667,0.062222,0.737567
std,389.855743,0.237575,84.914699,15.009875,0.751718,2307.855988,7849.754675,5.129287,0.376634,1.008401,0.306555,1.086949
min,1.000000,0.000000,0.000000,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,338.250000,0.000000,0.031140,40.000000,0.000000,564.880872,3300.000000,5.000000,0.000000,0.000000,0.000000,0.000000
50%,675.500000,0.000000,0.156891,52.000000,0.000000,1580.235058,5222.500000,8.000000,0.000000,1.000000,0.000000,0.000000
75%,1012.750000,0.000000,0.543145,63.000000,0.000000,2805.650385,8055.250000,11.000000,0.000000,2.000000,0.000000,1.000000
max,1350.000000,1.000000,2340.000000,97.000000,10.000000,32332.395495,208333.000000,31.000000,5.000000,8.000000,5.000000,8.000000

In [42]:
# считаем среднемесячный доход
MeanMonthlyIncome = df['Месячный доход'].mean()

# присываем среднемесячный доход, там где ходод не указан
df['Месячный доход'] = df['Месячный доход'].fillna( MeanMonthlyIncome )

df

,Id,Прогноз просрочки в течении 2 лет,"Остаток на кред.картах, %",Возраст,Кол-во просрочек 30-59 дней,"Платежей от долга, % или абс.платеж",Месячный доход,Кол-во кредитов,Кол-во просрочек на 90 дней и более,Кол-во ипотек,Кол-во сред.просрочек (60-89 дней) за 2 года,Кол-во иждевенцев в семье
0,1,1,0.766127,45,2,7323.197016,9120.000000,13,0,6,0,2.0
1,2,0,0.957151,40,0,316.878123,2600.000000,4,0,0,0,1.0
2,3,0,0.658180,38,1,258.914887,3042.000000,2,1,0,0,0.0
3,4,0,0.233810,30,0,118.963951,3300.000000,5,0,0,0,0.0
4,5,0,0.907239,49,1,1584.975094,63588.000000,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1346,0,0.000000,39,0,232.944085,4166.000000,5,0,0,0,0.0
1346,1347,0,0.045694,49,0,1200.699824,4000.000000,14,0,1,0,1.0
1347,1348,0,0.022780,53,0,3230.676930,10000.000000,14,0,2,0,1.0
1348,1349,0,0.036934,56,0,2407.712069,8362.000000,8,0,1,0,2.0
1349,1350,0,0.000000,62,0,NaN,6438.473492,5,0,1,0,0.0

In [43]:
# вероятность невозврата кредита по полю 'Прогноз просрочки в течении 2 лет'
# от кол-ва иждивенцев и от кол-ва взятых ипотек

# смотрим прогноз по возврату и невозврату для одной и той же группы кредиторов
# например, для группы из 3-х иждевенцев 5 вернули, 10 не вернули, тогда вер-сть невозврата: Р(3) = 10/15 = 0.66666(6)
df[ df['Прогноз просрочки в течении 2 лет'] == 1 ]

,Id,Прогноз просрочки в течении 2 лет,"Остаток на кред.картах, %",Возраст,Кол-во просрочек 30-59 дней,"Платежей от долга, % или абс.платеж",Месячный доход,Кол-во кредитов,Кол-во просрочек на 90 дней и более,Кол-во ипотек,Кол-во сред.просрочек (60-89 дней) за 2 года,Кол-во иждевенцев в семье
0,1,1,0.766127,45,2,7323.197016,9120.0,13,0,6,0,2.0
13,14,1,0.964673,40,3,5246.617034,13700.0,9,3,1,1,2.0
21,22,1,0.025656,38,0,1427.524158,3000.0,7,0,1,0,2.0
25,26,1,0.392248,50,0,7459.404749,4676.0,14,0,3,0,1.0
51,52,1,0.728150,31,0,2474.175276,3000.0,10,0,2,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1299,1300,1,1.000000,30,0,84.984891,5625.0,2,0,0,0,1.0
1311,1312,1,0.983078,42,0,3980.115531,4500.0,17,0,2,0,2.0
1313,1314,1,0.972151,59,0,2726.526202,1850.0,12,0,2,0,0.0
1338,1339,1,0.617026,26,0,549.839089,3417.0,5,0,0,0,0.0
1339,1340,1,0.409985,69,1,4087.720016,14600.0,15,0,2,0,0.0

In [76]:
# прогноз невозварта
df_no_ret_A = df[ df['Прогноз просрочки в течении 2 лет'] == 1 ].groupby('Кол-во иждевенцев в семье').count()['Прогноз просрочки в течении 2 лет']
df_no_ret_A

Кол-во иждевенцев в семье
0.0    32
1.0    23
2.0    19
3.0     4
4.0     1
Name: Прогноз просрочки в течении 2 лет, dtype: int64

In [77]:
# прогноз возварта
df_ret_A = df[ df['Прогноз просрочки в течении 2 лет'] == 0 ].groupby('Кол-во иждевенцев в семье').count()['Прогноз просрочки в течении 2 лет']
df_ret_A

Кол-во иждевенцев в семье
0.0    741
1.0    233
2.0    153
3.0     66
4.0     29
5.0      4
6.0      1
8.0      1
Name: Прогноз просрочки в течении 2 лет, dtype: int64

In [78]:
# вер-сть невозврата по кол-ву иждевенцев
# для групп 5,6,8 иждевенцев нет оценки вероятности
df_no_ret_A / (df_ret_A + df_no_ret_A)

Кол-во иждевенцев в семье
0.0    0.041397
1.0    0.089844
2.0    0.110465
3.0    0.057143
4.0    0.033333
5.0         NaN
6.0         NaN
8.0         NaN
Name: Прогноз просрочки в течении 2 лет, dtype: float64

In [79]:
# аналогично для группы по кол-ву взятых ипотек
df_no_ret_B = df[ df['Прогноз просрочки в течении 2 лет'] == 1 ].groupby('Кол-во ипотек').count()['Прогноз просрочки в течении 2 лет']
df_no_ret_B

Кол-во ипотек
0    29
1    23
2    18
3     8
4     2
6     1
Name: Прогноз просрочки в течении 2 лет, dtype: int64

In [80]:
df_ret_B = df[ df['Прогноз просрочки в течении 2 лет'] == 0 ].groupby('Кол-во ипотек').count()['Прогноз просрочки в течении 2 лет']
df_ret_B

Кол-во ипотек
0    481
1    449
2    267
3     47
4     17
5      7
8      1
Name: Прогноз просрочки в течении 2 лет, dtype: int64

In [81]:
# вер-сть невозврата по кол-ву ипотек
# для групп 5,6,8 иждевенцев нет оценки вероятности
df_no_ret_B / (df_ret_B + df_no_ret_B)

Кол-во ипотек
0    0.056863
1    0.048729
2    0.063158
3    0.145455
4    0.105263
5         NaN
6         NaN
8         NaN
Name: Прогноз просрочки в течении 2 лет, dtype: float64